version: '3.8'

services:
  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data_db:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - full_network

  db_test:
    container_name: db_test
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5433:5432
    volumes:
      - postgres_data_db_test:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - full_network

  project:
    container_name: project
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - db_test
    networks:
      - full_network


  test_service:
    container_name: test_service
    build:
      context: ./test_service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    networks:
      - full_network

volumes:
  postgres_data_db: {}
  postgres_data_db_test: {}
networks:
  full_network:
